server:
  port: 9000

spring:
  profiles:
    active: local

  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        query:
          plan_cache_max_size: 1024
          plan_parameter_metadata_max_size: 64
          in_clause_parameter_padding: true

jwt:
  secret: 25ee72370a7519d62cd6c9b3aa6896bf1f5be86fb7268b962779142e02c7f998

springdoc:
  api-docs:
    version: openapi_3_0
    path: /api-docs/json
    enabled: true
    groups:
      enabled: true
  cache:
    disabled: true
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /api-docs
    tags-sorter: alpha
    operations-sorter: alpha
  packages-to-scan: com.delivery.kyh

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:delivery
      username: sa
      password:
      driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
